// Educational content in Bahasa Indonesia and English — the same material as the Unity version
// (Assets/Scripts/Data/DefaultContent.cs). Every text is L("Bahasa Indonesia", "English").
// Hotspot positions use the Unity model space (x, y, z) and are converted in models.js.
const L = (id, en) => ({ id, en });

export const hardware = [
  {
    id: 'cpu', name: 'CPU', target: 0, icon: 'cpu', category: 'processing', image: 'CPU_Target',
    fullName: L('Central Processing Unit', 'Central Processing Unit'),
    short: L('Otak komputer yang menjalankan instruksi program.', 'The brain of the computer that runs program instructions.'),
    detail: L('CPU (Central Processing Unit) mengambil instruksi dari memori, menerjemahkannya, lalu mengeksekusinya. Di dalam CPU terdapat Control Unit (CU) yang mengatur urutan kerja, Arithmetic Logic Unit (ALU) yang menghitung dan membandingkan data, serta register sebagai tempat penyimpanan sangat cepat berukuran kecil. Siklus kerjanya disebut fetch – decode – execute.',
      'The CPU (Central Processing Unit) fetches instructions from memory, decodes them and executes them. Inside the CPU are the Control Unit (CU), which directs the order of work, the Arithmetic Logic Unit (ALU), which calculates and compares data, and registers, which are tiny, very fast storage locations. This work cycle is called fetch – decode – execute.'),
    fn: L('Memproses instruksi dan data: menghitung, membandingkan, dan mengatur kerja komponen lain.', 'Processes instructions and data: it calculates, compares and coordinates the other components.'),
    example: L('Saat kamu menekan tombol "=" di aplikasi kalkulator, ALU di dalam CPU yang menghitung hasilnya.', 'When you press "=" in a calculator app, the ALU inside the CPU works out the result.'),
    hotspots: [
      { id: 'alu', pos: [-0.17, 0.2, 0.12], label: L('ALU (Arithmetic Logic Unit)', 'ALU (Arithmetic Logic Unit)'),
        text: L('ALU melakukan operasi aritmetika (tambah, kurang, kali, bagi) dan operasi logika (membandingkan, AND, OR). Contoh: menghitung nilai rata-rata rapor.', 'The ALU performs arithmetic (add, subtract, multiply, divide) and logic operations (compare, AND, OR). Example: calculating the average of your report card grades.') },
      { id: 'control_unit', pos: [0.17, 0.2, 0.12], label: L('Control Unit (CU)', 'Control Unit (CU)'),
        text: L('Control Unit mengambil instruksi dari memori, menerjemahkannya, lalu memberi sinyal kepada ALU, memori, dan perangkat input/output. Ia seperti dirigen yang mengatur orkestra.', 'The Control Unit fetches instructions from memory, decodes them and sends signals to the ALU, memory and input/output devices. It is like a conductor leading an orchestra.') },
      { id: 'registers', pos: [0, 0.2, -0.16], label: L('Register & Cache', 'Registers & Cache'),
        text: L('Register dan cache adalah memori super cepat di dalam CPU. Data yang sedang diproses disimpan di sini agar CPU tidak perlu menunggu RAM.', 'Registers and cache are super-fast memory inside the CPU. Data being processed is kept here so the CPU does not have to wait for RAM.') },
    ],
  },
  {
    id: 'memory', name: 'RAM', target: 1, icon: 'memory-stick', category: 'memory', image: 'Memory_Target',
    fullName: L('Random Access Memory', 'Random Access Memory'),
    short: L('Memori kerja sementara untuk program dan data yang sedang dipakai.', 'Temporary working memory for the programs and data in use.'),
    detail: L('RAM menyimpan program dan data yang sedang digunakan agar CPU dapat mengaksesnya dengan cepat. RAM bersifat volatile: isinya hilang ketika komputer dimatikan. Semakin besar kapasitas RAM, semakin banyak program yang dapat dibuka bersamaan tanpa melambat.',
      'RAM holds the programs and data currently in use so the CPU can reach them quickly. RAM is volatile: its contents disappear when the computer is switched off. The more RAM a computer has, the more programs it can run at the same time without slowing down.'),
    fn: L('Menyimpan sementara instruksi dan data yang sedang diproses CPU.', 'Temporarily stores the instructions and data the CPU is working on.'),
    example: L('Saat kamu membuka banyak tab browser sekaligus, setiap tab memakai ruang di RAM.', 'When you open many browser tabs at once, every tab takes up space in RAM.'),
    hotspots: [
      { id: 'chips', pos: [-0.22, 0.24, 0.06], label: L('Chip Memori', 'Memory Chips'),
        text: L('Chip-chip hitam ini berisi jutaan sel memori kecil tempat data disimpan sementara dalam bentuk bit 0 dan 1.', 'These black chips contain millions of tiny memory cells where data is temporarily stored as bits (0 and 1).') },
      { id: 'contacts', pos: [0.25, 0.05, 0.06], label: L('Pin Kontak Emas', 'Gold Contact Pins'),
        text: L('Pin kontak menghubungkan modul RAM ke slot di motherboard sehingga data dapat mengalir ke CPU.', 'The contact pins connect the RAM module to its motherboard slot so data can flow to the CPU.') },
      { id: 'volatile', pos: [0.3, 0.3, 0.06], label: L('Sifat Volatile', 'Volatile Memory'),
        text: L('RAM hanya menyimpan data selama ada listrik. Karena itu, simpan pekerjaanmu ke storage sebelum mematikan komputer.', 'RAM only keeps data while it has power. That is why you should save your work to storage before switching off.') },
    ],
  },
  {
    id: 'storage', name: 'Storage', target: 2, icon: 'hard-drive', category: 'storage', image: 'Storage_Target',
    fullName: L('Penyimpanan (SSD / HDD)', 'Storage (SSD / HDD)'),
    short: L('Tempat menyimpan file dan program secara permanen.', 'Where files and programs are kept permanently.'),
    detail: L('Storage seperti SSD dan HDD menyimpan sistem operasi, aplikasi, dan file secara permanen (non-volatile), sehingga data tetap ada walaupun komputer dimatikan. SSD memakai chip flash sehingga lebih cepat daripada HDD yang memakai piringan magnetik berputar.',
      'Storage such as SSDs and HDDs keeps the operating system, apps and files permanently (non-volatile), so data stays even when the computer is switched off. SSDs use flash chips, which makes them faster than HDDs, which use spinning magnetic disks.'),
    fn: L('Menyimpan data secara permanen dan memuatnya ke RAM ketika dibutuhkan.', 'Stores data permanently and loads it into RAM when needed.'),
    example: L('Foto dan dokumen tugas sekolah yang kamu simpan tetap ada besok karena tersimpan di storage.', 'The photos and homework documents you save are still there tomorrow because they are kept in storage.'),
    hotspots: [
      { id: 'nand', pos: [-0.2, 0.1, 0], label: L('Chip Flash (NAND)', 'Flash Chips (NAND)'),
        text: L('Chip flash menyimpan data tanpa memerlukan listrik, sehingga file tetap aman setelah komputer dimatikan.', 'Flash chips keep data without power, so your files stay safe after the computer is switched off.') },
      { id: 'controller', pos: [0.12, 0.1, 0], label: L('Controller', 'Controller'),
        text: L('Controller mengatur di mana data ditulis dan dibaca, serta menjaga agar chip flash awet.', 'The controller decides where data is written and read, and keeps the flash chips healthy.') },
      { id: 'connector', pos: [0.46, 0.08, 0], label: L('Konektor', 'Connector'),
        text: L('Konektor menghubungkan storage ke motherboard. Data dari storage dimuat ke RAM sebelum diproses CPU.', 'The connector links the storage to the motherboard. Data from storage is loaded into RAM before the CPU processes it.') },
    ],
  },
  {
    id: 'keyboard', name: 'Keyboard', target: 3, icon: 'keyboard', category: 'input', image: 'Keyboard_Target',
    fullName: L('Papan Ketik', 'Keyboard'),
    short: L('Perangkat input untuk mengetik huruf, angka, dan perintah.', 'An input device for typing letters, numbers and commands.'),
    detail: L('Keyboard mengubah setiap tekanan tombol menjadi kode digital yang dikirim ke komputer. Kode ini masuk ke memori, lalu diproses CPU sehingga huruf muncul di layar.',
      'A keyboard turns every key press into a digital code that is sent to the computer. The code goes into memory and is processed by the CPU, so the letter appears on the screen.'),
    fn: L('Memasukkan data teks dan perintah ke komputer.', 'Enters text and commands into the computer.'),
    example: L('Mengetik nama dan alamat saat mengisi formulir pendaftaran online.', 'Typing your name and address when filling in an online registration form.'),
    hotspots: [
      { id: 'letters', pos: [-0.15, 0.12, 0.02], label: L('Tombol Huruf & Angka', 'Letter & Number Keys'),
        text: L('Setiap tombol memiliki kode unik. Saat ditekan, kode dikirim ke komputer sebagai input.', 'Every key has a unique code. When pressed, the code is sent to the computer as input.') },
      { id: 'enter', pos: [0.38, 0.12, 0], label: L('Tombol Enter', 'Enter Key'),
        text: L('Tombol Enter mengirim perintah untuk menjalankan atau mengonfirmasi, misalnya mengirim pesan.', 'The Enter key sends a command to run or confirm something, such as sending a message.') },
      { id: 'cable', pos: [0, 0.1, -0.27], label: L('Kabel / Koneksi', 'Cable / Connection'),
        text: L('Data dari keyboard dikirim melalui kabel USB atau secara nirkabel (Bluetooth) ke komputer.', 'Data from the keyboard travels to the computer through a USB cable or wirelessly (Bluetooth).') },
    ],
  },
  {
    id: 'mouse', name: 'Mouse', target: 4, icon: 'mouse', category: 'input', image: 'Mouse_Target',
    fullName: L('Tetikus', 'Mouse'),
    short: L('Perangkat input penunjuk untuk menggerakkan kursor.', 'A pointing input device that moves the cursor.'),
    detail: L('Mouse mendeteksi gerakan tangan melalui sensor optik dan mengirimkan posisi serta klik ke komputer.', 'A mouse detects hand movement with an optical sensor and sends the position and clicks to the computer.'),
    fn: L('Menggerakkan kursor dan memilih objek di layar.', 'Moves the cursor and selects things on the screen.'),
    example: L('Mengklik tombol "Kirim" saat mengumpulkan tugas di Google Classroom.', 'Clicking "Submit" when you hand in homework on Google Classroom.'),
    hotspots: [
      { id: 'buttons', pos: [-0.08, 0.2, 0.14], label: L('Tombol Kiri & Kanan', 'Left & Right Buttons'),
        text: L('Tombol kiri untuk memilih/klik, tombol kanan untuk membuka menu tambahan.', 'The left button selects/clicks; the right button opens an extra menu.') },
      { id: 'wheel', pos: [0, 0.22, 0.1], label: L('Roda Gulir', 'Scroll Wheel'),
        text: L('Roda gulir menggulung halaman ke atas atau ke bawah.', 'The scroll wheel moves the page up or down.') },
      { id: 'sensor', pos: [0, 0.03, 0.26], label: L('Sensor Optik', 'Optical Sensor'),
        text: L('Sensor cahaya di bawah mouse membaca gerakan pada permukaan meja ribuan kali per detik.', 'A light sensor under the mouse reads movement on the desk thousands of times per second.') },
    ],
  },
  {
    id: 'monitor', name: 'Monitor', target: 5, icon: 'monitor', category: 'output', image: 'Monitor_Target',
    fullName: L('Layar Tampilan', 'Display Screen'),
    short: L('Perangkat output yang menampilkan hasil proses dalam bentuk gambar.', 'An output device that shows the results of processing as images.'),
    detail: L('Monitor menampilkan informasi dari komputer menggunakan jutaan titik kecil bernama piksel. Setiap piksel tersusun dari warna merah, hijau, dan biru (RGB).', 'A monitor shows information from the computer using millions of tiny dots called pixels. Each pixel is made of red, green and blue light (RGB).'),
    fn: L('Menampilkan teks, gambar, dan video hasil proses komputer.', 'Displays the text, images and video produced by the computer.'),
    example: L('Menonton video pembelajaran atau melihat hasil ketikanmu di layar.', 'Watching a learning video or seeing what you have typed on the screen.'),
    hotspots: [
      { id: 'pixels', pos: [-0.2, 0.55, 0.04], label: L('Layar & Piksel', 'Screen & Pixels'),
        text: L('Gambar di layar tersusun dari piksel. Resolusi 1920×1080 berarti ada lebih dari dua juta piksel.', 'The picture is made of pixels. A resolution of 1920×1080 means more than two million pixels.') },
      { id: 'port', pos: [0.3, 0.4, -0.05], label: L('Port Video (HDMI)', 'Video Port (HDMI)'),
        text: L('Kabel HDMI membawa sinyal gambar dari kartu grafis komputer ke monitor.', "An HDMI cable carries the picture signal from the computer's graphics card to the monitor.") },
      { id: 'stand', pos: [0, 0.12, 0.1], label: L('Penyangga & Tombol', 'Stand & Buttons'),
        text: L('Tombol pada monitor untuk menyalakan dan mengatur kecerahan agar nyaman di mata.', 'The buttons turn the monitor on and adjust brightness so it is comfortable for your eyes.') },
    ],
  },
  {
    id: 'printer', name: 'Printer', target: 6, icon: 'printer', category: 'output', image: 'Printer_Target',
    fullName: L('Pencetak', 'Printer'),
    short: L('Perangkat output yang mencetak dokumen ke kertas.', 'An output device that prints documents on paper.'),
    detail: L('Printer menerima data dokumen dari komputer lalu mencetaknya ke kertas menggunakan tinta (inkjet) atau toner (laser).', 'A printer receives document data from the computer and prints it on paper using ink (inkjet) or toner (laser).'),
    fn: L('Menghasilkan salinan cetak (hardcopy) dari dokumen digital.', 'Produces a printed copy (hard copy) of a digital document.'),
    example: L('Mencetak kartu ujian atau laporan tugas untuk dikumpulkan ke guru.', 'Printing an exam card or a report to hand in to your teacher.'),
    hotspots: [
      { id: 'tray_in', pos: [0, 0.45, -0.25], label: L('Baki Kertas Masuk', 'Paper Input Tray'),
        text: L('Kertas kosong diletakkan di sini sebelum ditarik ke dalam printer.', 'Blank paper is placed here before it is pulled into the printer.') },
      { id: 'head', pos: [0.2, 0.36, 0.05], label: L('Kepala Cetak / Toner', 'Print Head / Toner'),
        text: L('Bagian ini menaruh tinta atau toner di atas kertas sesuai data dari komputer.', 'This part puts ink or toner on the paper according to the data from the computer.') },
      { id: 'tray_out', pos: [0, 0.12, 0.35], label: L('Baki Kertas Keluar', 'Paper Output Tray'),
        text: L('Hasil cetakan keluar di sini sebagai output yang bisa dipegang.', 'The printed pages come out here as output you can hold.') },
    ],
  },
  {
    id: 'speaker', name: 'Speaker', target: 7, icon: 'speaker', category: 'output', image: 'Speaker_Target',
    fullName: L('Pengeras Suara', 'Loudspeaker'),
    short: L('Perangkat output yang menghasilkan suara.', 'An output device that produces sound.'),
    detail: L('Speaker mengubah sinyal listrik dari komputer menjadi getaran udara yang kita dengar sebagai suara.', 'A speaker turns electrical signals from the computer into vibrations in the air that we hear as sound.'),
    fn: L('Mengeluarkan audio seperti musik, narasi, dan suara notifikasi.', 'Plays audio such as music, narration and notification sounds.'),
    example: L('Mendengarkan narasi pelajaran atau suara video pembelajaran.', 'Listening to lesson narration or the sound of a learning video.'),
    hotspots: [
      { id: 'woofer', pos: [0, 0.25, 0.22], label: L('Woofer', 'Woofer'),
        text: L('Woofer adalah membran besar yang menghasilkan suara rendah (bass).', 'The woofer is a large cone that produces low sounds (bass).') },
      { id: 'tweeter', pos: [0, 0.55, 0.22], label: L('Tweeter', 'Tweeter'),
        text: L('Tweeter adalah membran kecil yang menghasilkan suara tinggi yang jernih.', 'The tweeter is a small cone that produces clear high sounds.') },
      { id: 'amp', pos: [0.15, 0.1, -0.22], label: L('Kabel Audio', 'Audio Cable'),
        text: L('Sinyal suara dari komputer masuk melalui kabel audio atau Bluetooth.', 'The sound signal from the computer arrives through an audio cable or Bluetooth.') },
    ],
  },
  {
    id: 'von_neumann', name: 'Von Neumann', target: 8, icon: 'workflow', category: 'architecture', image: 'VonNeumann_Target',
    fullName: L('Arsitektur Von Neumann', 'Von Neumann Architecture'),
    short: L('Model dasar cara kerja komputer modern.', 'The basic model of how modern computers work.'),
    detail: L('Arsitektur Von Neumann menjelaskan bahwa program dan data disimpan bersama di memori. CPU mengambil instruksi dan data dari memori melalui bus, memprosesnya, lalu mengirim hasilnya ke memori atau perangkat output. Komponen utamanya: unit input, CPU (Control Unit dan ALU), memori, penyimpanan, dan unit output.',
      'The Von Neumann architecture says that programs and data are stored together in memory. The CPU fetches instructions and data from memory over the bus, processes them and sends the results to memory or an output device. Its main parts are the input unit, the CPU (Control Unit and ALU), memory, storage and the output unit.'),
    fn: L('Menjelaskan hubungan dan alur data antara input, CPU, memori, penyimpanan, dan output.', 'Explains how input, the CPU, memory, storage and output are connected and how data flows between them.'),
    example: L('Saat kamu mengetik huruf "A": keyboard (input) › memori › CPU memproses › monitor (output) menampilkan "A".', 'When you type the letter "A": keyboard (input) › memory › the CPU processes it › the monitor (output) shows "A".'),
    hotspots: [
      { id: 'input', pos: [-0.42, 0.3, 0.1], label: L('Unit Input', 'Input Unit'), text: L('Data masuk dari perangkat input seperti keyboard dan mouse.', 'Data comes in from input devices such as the keyboard and mouse.') },
      { id: 'cpu', pos: [0, 0.36, 0.1], label: L('CPU (CU + ALU)', 'CPU (CU + ALU)'), text: L('CPU mengambil, menerjemahkan, dan mengeksekusi instruksi.', 'The CPU fetches, decodes and executes instructions.') },
      { id: 'memory', pos: [0, 0.3, -0.3], label: L('Memori (RAM)', 'Memory (RAM)'), text: L('Program dan data disimpan bersama di memori — inilah ciri utama Von Neumann.', 'Programs and data are stored together in memory — the key idea of Von Neumann.') },
      { id: 'output', pos: [0.42, 0.3, 0.1], label: L('Unit Output', 'Output Unit'), text: L('Hasil proses dikirim ke perangkat output seperti monitor dan printer.', 'Results are sent to output devices such as the monitor and printer.') },
      { id: 'bus', pos: [-0.2, 0.12, -0.12], label: L('Bus Sistem', 'System Bus'), text: L('Bus adalah jalur yang membawa data, alamat, dan sinyal kontrol antar komponen.', 'The bus is the pathway that carries data, addresses and control signals between components.') },
    ],
  },
];

const Q = (id, type, hw, text, correct, explanation, options = [], extra = {}) =>
  ({ id, type, hw, text, correct, explanation, options, ...extra });

// options: array of L(); correct: index (single choice) | accepted answers (identification) | null (ordering: options already in order)
export const questions = [
  Q('q_cpu_alu', 'mc', 'cpu', L('Bagian CPU yang bertugas melakukan perhitungan dan perbandingan adalah …', 'Which part of the CPU carries out calculations and comparisons?'), 0,
    L('ALU menangani operasi aritmetika dan logika. Control Unit mengatur, bukan menghitung.', 'The ALU handles arithmetic and logic. The Control Unit coordinates; it does not calculate.'),
    [L('ALU', 'ALU'), L('Control Unit', 'Control Unit'), L('Register', 'Register'), L('Monitor', 'Monitor')]),
  Q('q_vn_tf', 'tf', 'von_neumann', L('Pada arsitektur Von Neumann, program dan data disimpan di memori yang sama.', 'In the Von Neumann architecture, programs and data are stored in the same memory.'), 0,
    L('Benar. Menyimpan program dan data di memori yang sama adalah ciri utama arsitektur Von Neumann.', 'True. Storing programs and data in the same memory is the key feature of the Von Neumann architecture.'),
    [L('Benar', 'True'), L('Salah', 'False')]),
  Q('q_cycle_order', 'order', 'cpu', L('Urutkan siklus kerja CPU dari langkah pertama.', 'Put the CPU work cycle in order, starting with the first step.'), null,
    L('CPU selalu mengambil instruksi (fetch), menerjemahkannya (decode), lalu mengeksekusinya (execute).', 'The CPU always fetches an instruction, decodes it and then executes it.'),
    [L('Fetch (ambil instruksi)', 'Fetch (get the instruction)'), L('Decode (terjemahkan)', 'Decode (interpret it)'), L('Execute (jalankan)', 'Execute (carry it out)')]),
  Q('q_cpu_ar', 'ar', 'cpu', L('Pindai target CPU. Ketuk bagian yang mengatur urutan kerja semua komponen. Bagian apakah itu?', 'Scan the CPU target. Tap the part that coordinates the work of all components. Which part is it?'), 0,
    L('Control Unit (CU) memberi sinyal pengatur ke ALU, memori, dan perangkat input/output.', 'The Control Unit (CU) sends control signals to the ALU, memory and input/output devices.'),
    [L('Control Unit', 'Control Unit'), L('ALU', 'ALU'), L('Register & Cache', 'Registers & Cache')]),
  Q('q_ram_volatile', 'mc', 'memory', L('Mengapa tugas yang belum disimpan bisa hilang saat listrik padam?', 'Why can unsaved work be lost when the power goes out?'), 0,
    L('RAM hanya menyimpan data selama ada listrik. Data yang belum disimpan ke storage akan hilang.', 'RAM only keeps data while it has power. Anything not yet saved to storage is lost.'),
    [L('Karena RAM bersifat volatile', 'Because RAM is volatile'), L('Karena storage rusak', 'Because the storage is broken'), L('Karena CPU terlalu panas', 'Because the CPU is too hot'), L('Karena monitor mati', 'Because the monitor is off')]),
  Q('q_storage_id', 'id', 'storage', L('Sebutkan jenis penyimpanan yang memakai chip flash dan lebih cepat daripada HDD (singkatan 3 huruf).', 'Name the type of storage that uses flash chips and is faster than an HDD (3-letter abbreviation).'),
    ['SSD', 'solid state drive', 'solid-state drive'],
    L('SSD (Solid State Drive) memakai chip flash tanpa bagian bergerak sehingga lebih cepat daripada HDD.', 'An SSD (Solid State Drive) uses flash chips with no moving parts, so it is faster than an HDD.')),
  Q('q_mem_match', 'match', 'memory', L('Jodohkan komponen dengan sifatnya.', 'Match each component with its property.'), null,
    L('RAM cepat tetapi sementara; storage permanen; register paling cepat dan paling kecil, berada di dalam CPU.', 'RAM is fast but temporary; storage is permanent; registers are the fastest and smallest, inside the CPU.'), [],
    { pairs: [[L('RAM', 'RAM'), L('Sementara (volatile)', 'Temporary (volatile)')], [L('SSD', 'SSD'), L('Permanen (non-volatile)', 'Permanent (non-volatile)')], [L('Register', 'Register'), L('Paling cepat, di dalam CPU', 'Fastest, inside the CPU')]] }),
  Q('q_io_match', 'match', 'keyboard', L('Jodohkan perangkat dengan jenisnya.', 'Match each device with its type.'), null,
    L('Keyboard dan mouse memasukkan data (input). Printer dan speaker mengeluarkan hasil (output).', 'The keyboard and mouse put data in (input). The printer and speaker give results out (output).'), [],
    { pairs: [[L('Keyboard', 'Keyboard'), L('Input', 'Input')], [L('Printer', 'Printer'), L('Output', 'Output')], [L('Mouse', 'Mouse'), L('Input', 'Input')], [L('Speaker', 'Speaker'), L('Output', 'Output')]] }),
  Q('q_io_mc', 'mc', 'monitor', L('Perangkat manakah yang termasuk perangkat output?', 'Which of these is an output device?'), 2,
    L('Monitor menampilkan hasil proses komputer, sehingga termasuk perangkat output.', "A monitor displays the computer's results, so it is an output device."),
    [L('Keyboard', 'Keyboard'), L('Mouse', 'Mouse'), L('Monitor', 'Monitor'), L('Scanner', 'Scanner')]),
  Q('q_speaker_tf', 'tf', 'speaker', L('Speaker adalah perangkat input karena mengeluarkan suara.', 'A speaker is an input device because it produces sound.'), 1,
    L('Salah. Speaker mengeluarkan suara dari komputer, jadi termasuk perangkat output.', 'False. A speaker sends sound out of the computer, so it is an output device.'),
    [L('Benar', 'True'), L('Salah', 'False')]),
  Q('q_flow_order', 'order', 'von_neumann', L('Urutkan alur data saat kamu mengetik huruf "A" hingga muncul di layar.', 'Put in order how data flows when you type the letter "A" until it appears on the screen.'), null,
    L('Data masuk dari keyboard, disimpan di memori, diproses CPU, lalu ditampilkan monitor.', 'Data comes in from the keyboard, is stored in memory, is processed by the CPU and is shown on the monitor.'),
    [L('Keyboard (input)', 'Keyboard (input)'), L('Memori (RAM)', 'Memory (RAM)'), L('CPU memproses', 'CPU processes'), L('Monitor (output)', 'Monitor (output)')]),
  Q('q_bus_mc', 'mc', 'von_neumann', L('Jalur yang membawa data antar komponen komputer disebut …', 'The pathway that carries data between computer components is called …'), 0,
    L('Bus sistem membawa data, alamat, dan sinyal kontrol antara CPU, memori, dan perangkat I/O.', 'The system bus carries data, addresses and control signals between the CPU, memory and I/O devices.'),
    [L('Bus sistem', 'The system bus'), L('Kabel power', 'The power cable'), L('Piksel', 'A pixel'), L('Register', 'A register')]),
  // scenario tasks
  Q('q_sc_video', 'ctx', 'cpu', L('Laptop Rani sangat lambat saat merender video dan Task Manager menunjukkan penggunaan CPU 100%. Komponen mana yang paling bekerja keras?', "Rani's laptop is very slow while rendering a video, and Task Manager shows 100% CPU usage. Which component is working hardest?"), 0,
    L('Rendering video membutuhkan banyak perhitungan, sehingga CPU (terutama ALU) bekerja sangat keras.', 'Rendering video needs a huge number of calculations, so the CPU (especially the ALU) works very hard.'),
    [L('CPU', 'CPU'), L('Speaker', 'Speaker'), L('Mouse', 'Mouse'), L('Printer', 'Printer')]),
  Q('q_sc_tabs', 'ctx', 'memory', L('Dimas membuka 30 tab browser dan laptopnya mulai tersendat. Upaya paling tepat adalah …', 'Dimas opens 30 browser tabs and his laptop starts to stutter. What is the best thing to do?'), 0,
    L('Setiap tab memakai RAM. Menutup tab yang tidak dipakai mengosongkan RAM sehingga laptop kembali lancar.', 'Every tab uses RAM. Closing unused tabs frees RAM so the laptop runs smoothly again.'),
    [L('Menutup tab yang tidak dipakai agar RAM lega', 'Close unused tabs to free up RAM'), L('Mengganti mouse', 'Replace the mouse'), L('Menambah kecerahan monitor', 'Turn up the monitor brightness'), L('Mencabut speaker', 'Unplug the speaker')]),
  Q('q_sc_photos', 'ctx', 'storage', L('Ponsel Sari menampilkan pesan "Penyimpanan penuh" saat menyimpan foto kegiatan kelas. Komponen apa yang penuh?', 'Sari\'s phone shows "Storage full" when she saves photos of a class activity. Which component is full?'), 0,
    L('Foto disimpan permanen di storage. Pesan itu berarti ruang storage habis, bukan RAM.', 'Photos are kept permanently in storage. The message means storage space has run out, not RAM.'),
    [L('Storage', 'Storage'), L('RAM', 'RAM'), L('CPU', 'CPU'), L('Layar', 'Screen')]),
  Q('q_sc_cashier', 'ctx', 'keyboard', L('Kasir mengetik jumlah barang, lalu struk dicetak. Manakah pasangan input dan output yang tepat?', 'A cashier types in the number of items, then a receipt is printed. Which input and output pair is correct?'), 0,
    L('Keyboard memasukkan data (input); printer mencetak struk (output).', 'The keyboard enters data (input); the printer prints the receipt (output).'),
    [L('Keyboard › Printer', 'Keyboard › Printer'), L('Printer › Keyboard', 'Printer › Keyboard'), L('Monitor › Mouse', 'Monitor › Mouse'), L('Speaker › Keyboard', 'Speaker › Keyboard')]),
  Q('q_sc_typing', 'ctx', 'von_neumann', L('Saat Budi mengetik tugas, di mana huruf yang diketik disimpan sementara sebelum diproses CPU?', 'While Budi types his homework, where are the typed letters stored temporarily before the CPU processes them?'), 0,
    L('Data dari input disimpan dulu di memori (RAM), lalu diambil CPU untuk diproses.', 'Input data is first stored in memory (RAM), then the CPU fetches it for processing.'),
    [L('Memori (RAM)', 'Memory (RAM)'), L('Printer', 'Printer'), L('Speaker', 'Speaker'), L('Mouse', 'Mouse')]),
];

export const scenarios = [
  { id: 'sc_video_render', icon: 'cpu', hw: 'cpu', task: 'q_sc_video',
    title: L('Laptop Lambat Saat Render Video', 'Slow Laptop While Rendering a Video'), env: L('Rumah — mengerjakan tugas video', 'Home — working on a video assignment'),
    desc: L('Rani sedang mengedit video presentasi kelompok. Saat proses render, laptopnya sangat lambat dan kipasnya berbunyi keras. Di Task Manager, penggunaan CPU mencapai 100%.', "Rani is editing her group's presentation video. While it renders, her laptop becomes very slow and the fan is loud. Task Manager shows CPU usage at 100%."),
    question: L('Komponen apa yang sedang memproses jutaan perhitungan untuk menyusun video?', 'Which component is processing millions of calculations to build the video?'),
    feedback: L('Tepat sekali jika kamu memilih CPU. Render video terdiri atas banyak perhitungan yang dikerjakan ALU, sementara Control Unit mengatur urutannya. Menutup aplikasi lain dapat memberi CPU lebih banyak waktu untuk render.', 'The CPU is the right answer. Rendering video is made of many calculations done by the ALU, while the Control Unit organises their order. Closing other apps gives the CPU more time for rendering.'),
    reflection: L('Kapan kamu pernah merasakan komputer lambat karena CPU bekerja keras? Apa yang bisa kamu lakukan?', 'When have you noticed a computer slow down because the CPU was working hard? What could you do about it?') },
  { id: 'sc_browser_tabs', icon: 'memory-stick', hw: 'memory', task: 'q_sc_tabs',
    title: L('Terlalu Banyak Tab Browser', 'Too Many Browser Tabs'), env: L('Lab komputer sekolah', 'School computer lab'),
    desc: L('Dimas mencari referensi tugas dan membuka 30 tab browser. Lama-lama laptop tersendat, bahkan mengetik pun terasa lambat.', 'Dimas is researching his assignment and opens 30 browser tabs. Soon the laptop stutters and even typing feels slow.'),
    question: L('Di mana semua tab yang terbuka itu disimpan sementara?', 'Where are all those open tabs stored temporarily?'),
    feedback: L('Setiap tab browser disimpan di RAM. Jika RAM penuh, komputer memindahkan data ke storage yang jauh lebih lambat. Menutup tab yang tidak dipakai membuat RAM lega kembali.', 'Every browser tab is kept in RAM. When RAM is full, the computer moves data to much slower storage. Closing unused tabs frees up RAM again.'),
    reflection: L('Bagaimana kamu akan mengatur tab dan aplikasi saat belajar agar komputer tetap lancar?', 'How will you manage tabs and apps while studying so the computer keeps running smoothly?') },
  { id: 'sc_storage_full', icon: 'hard-drive', hw: 'storage', task: 'q_sc_photos',
    title: L('Penyimpanan Penuh', 'Storage Full'), env: L('Kegiatan kelas di luar sekolah', 'Class trip outside school'),
    desc: L('Sari ingin menyimpan foto kegiatan kelas, tetapi ponselnya menampilkan pesan "Penyimpanan penuh".', 'Sari wants to save photos of a class activity, but her phone shows the message "Storage full".'),
    question: L('Komponen mana yang menyimpan foto secara permanen?', 'Which component keeps photos permanently?'),
    feedback: L('Foto disimpan di storage agar tetap ada setelah ponsel dimatikan. Menghapus file yang tidak perlu atau memindahkannya ke cloud akan mengosongkan storage.', 'Photos are kept in storage so they are still there after the phone is switched off. Deleting files you do not need, or moving them to the cloud, frees up storage.'),
    reflection: L('File apa yang biasanya memenuhi penyimpanan perangkatmu, dan bagaimana kamu mengelolanya?', "What kinds of files usually fill up your device's storage, and how do you manage them?") },
  { id: 'sc_cashier', icon: 'printer', hw: 'keyboard', task: 'q_sc_cashier',
    title: L('Kasir Minimarket', 'Minimarket Cashier'), env: L('Minimarket dekat sekolah', 'Minimarket near school'),
    desc: L('Di minimarket, kasir mengetik jumlah barang, total belanja tampil di layar, lalu struk dicetak untuk pembeli.', 'At the minimarket, the cashier types in the number of items, the total appears on the screen and a receipt is printed.'),
    question: L('Perangkat mana yang memasukkan data, dan perangkat mana yang mengeluarkan hasil?', 'Which devices put data in, and which devices give results out?'),
    feedback: L('Keyboard dan pemindai barcode adalah perangkat input. Monitor, printer struk, dan speaker adalah perangkat output. CPU memproses total belanja di antaranya.', 'The keyboard and barcode scanner are input devices. The monitor, receipt printer and speaker are output devices. The CPU calculates the total in between.'),
    reflection: L('Sebutkan satu tempat lain di sekitarmu yang memakai perangkat input dan output. Apa saja perangkatnya?', 'Name another place around you that uses input and output devices. Which devices are they?') },
  { id: 'sc_typing_flow', icon: 'workflow', hw: 'von_neumann', task: 'q_sc_typing',
    title: L('Dari Ketikan ke Layar', 'From Keystroke to Screen'), env: L('Mengerjakan tugas di komputer', 'Doing homework on the computer'),
    desc: L('Budi mengetik tugas bahasa Indonesia. Setiap huruf yang ditekan langsung muncul di layar dalam sekejap.', 'Budi is typing his Indonesian homework. Every letter he presses appears on the screen in an instant.'),
    question: L('Melewati komponen apa saja sebuah huruf sebelum muncul di layar?', 'Which components does a letter pass through before it appears on the screen?'),
    feedback: L('Huruf dari keyboard (input) disimpan di memori, diambil dan diproses CPU, lalu hasilnya dikirim ke monitor (output). Semua melewati bus sistem sesuai arsitektur Von Neumann.', 'The letter from the keyboard (input) is stored in memory, fetched and processed by the CPU, and the result is sent to the monitor (output). Everything travels over the system bus, as in the Von Neumann architecture.'),
    reflection: L('Jelaskan dengan kata-katamu sendiri alur data ketika kamu mengirim pesan di ponsel.', 'In your own words, explain how data flows when you send a message on your phone.') },
];

// Lesson steps: ['vn'] | ['ar', hardwareId] | ['hw'] | ['sc', scenarioId] | ['practice'] | ['reflection']
export const modules = [
  { id: 'm1_cpu_vn', order: 1, icon: 'cpu', minutes: 25,
    title: L('Arsitektur Von Neumann & CPU', 'Von Neumann Architecture & the CPU'),
    desc: L('Kenali model Von Neumann dan cara CPU menjalankan instruksi melalui AR.', 'Discover the Von Neumann model and how the CPU runs instructions, through AR.'),
    reflection: L('Bagaimana pemahamanmu tentang tugas CPU dan hubungannya dengan memori setelah pelajaran ini?', "After this lesson, how well do you understand the CPU's job and how it works with memory?"),
    objectives: [L('Menjelaskan komponen utama arsitektur Von Neumann.', 'Explain the main components of the Von Neumann architecture.'),
      L('Membedakan fungsi Control Unit, ALU, dan register di dalam CPU.', 'Distinguish the roles of the Control Unit, ALU and registers in the CPU.'),
      L('Menghubungkan kerja CPU dengan situasi nyata sehari-hari.', 'Connect how the CPU works to everyday situations.')],
    hardware: ['von_neumann', 'cpu'], questions: ['q_cpu_alu', 'q_vn_tf', 'q_cycle_order', 'q_cpu_ar'],
    steps: [['vn'], ['ar', 'cpu'], ['sc', 'sc_video_render'], ['practice'], ['reflection']] },
  { id: 'm2_memory_storage', order: 2, icon: 'memory-stick', minutes: 20,
    title: L('Memori & Penyimpanan', 'Memory & Storage'),
    desc: L('Bandingkan RAM dan storage, serta pahami mengapa data bisa hilang.', 'Compare RAM and storage, and understand why data can be lost.'),
    reflection: L('Apa perbedaan RAM dan storage menurut kata-katamu sendiri?', 'In your own words, what is the difference between RAM and storage?'),
    objectives: [L('Membedakan memori volatile (RAM) dan non-volatile (storage).', 'Distinguish volatile memory (RAM) from non-volatile storage.'),
      L('Menjelaskan peran RAM saat program berjalan.', 'Explain the role of RAM while programs are running.'),
      L('Menerapkan cara mengelola memori dan penyimpanan perangkat.', "Apply ways to manage a device's memory and storage.")],
    hardware: ['memory', 'storage'], questions: ['q_ram_volatile', 'q_storage_id', 'q_mem_match'],
    steps: [['ar', 'memory'], ['sc', 'sc_browser_tabs'], ['ar', 'storage'], ['sc', 'sc_storage_full'], ['practice'], ['reflection']] },
  { id: 'm3_input_output', order: 3, icon: 'keyboard', minutes: 20,
    title: L('Perangkat Input & Output', 'Input & Output Devices'),
    desc: L('Jelajahi perangkat yang memasukkan data dan yang menampilkan hasil.', 'Explore the devices that put data in and the ones that show results.'),
    reflection: L('Perangkat input dan output apa yang paling sering kamu gunakan, dan untuk apa?', 'Which input and output devices do you use most often, and what for?'),
    objectives: [L('Mengelompokkan perangkat ke dalam input dan output.', 'Sort devices into input and output.'),
      L('Menjelaskan fungsi keyboard, mouse, monitor, printer, dan speaker.', 'Explain what the keyboard, mouse, monitor, printer and speaker do.'),
      L('Mengidentifikasi perangkat I/O dalam situasi nyata.', 'Identify I/O devices in real-life situations.')],
    hardware: ['keyboard', 'mouse', 'monitor', 'printer', 'speaker'], questions: ['q_io_match', 'q_io_mc', 'q_speaker_tf'],
    steps: [['hw'], ['ar', 'keyboard'], ['sc', 'sc_cashier'], ['practice'], ['reflection']] },
  { id: 'm4_data_flow', order: 4, icon: 'workflow', minutes: 20,
    title: L('Alur Data Antar Komponen', 'How Data Flows Between Components'),
    desc: L('Ikuti perjalanan data dari input, memori, CPU, hingga output.', 'Follow data on its journey from input through memory and the CPU to output.'),
    reflection: L('Setelah melihat alur data, bagian mana yang paling mudah dan paling sulit kamu pahami?', 'Now that you have seen the data flow, which part was easiest and which was hardest to understand?'),
    objectives: [L('Menjelaskan alur data input › memori › CPU › output.', 'Explain the data flow input › memory › CPU › output.'),
      L('Menjelaskan peran bus sistem.', 'Explain the role of the system bus.'),
      L('Menerapkan konsep alur data pada contoh nyata.', 'Apply the idea of data flow to real examples.')],
    hardware: ['von_neumann'], questions: ['q_flow_order', 'q_bus_mc'],
    steps: [['vn'], ['ar', 'von_neumann'], ['sc', 'sc_typing_flow'], ['practice'], ['reflection']] },
];

export const getHw = id => hardware.find(h => h.id === id);
export const getQ = id => questions.find(q => q.id === id);
export const getSc = id => scenarios.find(s => s.id === id);
export const getMod = id => modules.find(m => m.id === id);
export const categories = {
  processing: { color: '#1D4ED8', label: L('Pemrosesan', 'Processing') },
  memory: { color: '#6941C6', label: L('Memori', 'Memory') },
  storage: { color: '#B54708', label: L('Penyimpanan', 'Storage') },
  input: { color: '#0E7C86', label: L('Input', 'Input') },
  output: { color: '#C11574', label: L('Output', 'Output') },
  architecture: { color: '#3538CD', label: L('Arsitektur', 'Architecture') },
};
