using System;
using System.Collections.Generic;
using UnityEngine;

namespace ComputerExplorer.Data
{
    public enum HardwareCategory { Processing, Memory, Storage, Input, Output, Architecture }

    public static class HardwareCategoryExtensions
    {
        public static string DisplayName(this HardwareCategory c) => c switch
        {
            HardwareCategory.Processing => "Pemrosesan",
            HardwareCategory.Memory => "Memori",
            HardwareCategory.Storage => "Penyimpanan",
            HardwareCategory.Input => "Input",
            HardwareCategory.Output => "Output",
            HardwareCategory.Architecture => "Arsitektur",
            _ => c.ToString()
        };
    }

    /// <summary>An interactive point on a 3D hardware model (e.g. ALU on the CPU).</summary>
    [Serializable]
    public class HotspotData
    {
        public string hotspotId;
        public string label;
        [TextArea(2, 6)] public string description;
        [Tooltip("Position relative to the model root, in model units (model is ~1 unit wide).")]
        public Vector3 localPosition;
        public AudioClip narration;
    }

    /// <summary>Educational content for one hardware item. Edit these assets instead of code.</summary>
    [CreateAssetMenu(menuName = "Computer Explorer/Hardware Data", fileName = "Hardware_")]
    public class HardwareData : ScriptableObject
    {
        public string hardwareId;
        public string hardwareName;
        public string fullName;
        public HardwareCategory category;
        [TextArea(2, 4)] public string shortDescription;
        [TextArea(3, 8)] public string detailedDescription;
        [TextArea(2, 4)] public string function;
        [TextArea(2, 6)] public string contextualExample;

        [Header("Presentation")]
        [Tooltip("Optional. If empty, a procedural model is generated by HardwareModelFactory.")]
        public GameObject modelPrefab;
        [Tooltip("Optional recorded narration. If empty, Android Text-to-Speech (id-ID) reads the text.")]
        public AudioClip narration;
        public Sprite icon;
        [Tooltip("Icon file name in Resources/Icons, used when no sprite is assigned.")]
        public string iconName = "cpu";

        public List<HotspotData> hotspots = new List<HotspotData>();

        [Header("AR Target (Vuforia)")]
        [Tooltip("Target name in the Vuforia database, or name of the image in Resources/ARTargets.")]
        public string arTargetName;
        [Tooltip("Optional runtime image target. Must be readable (set automatically by ARTargetImportSettings).")]
        public Texture2D arTargetImage;
        public float printedWidthMeters = Core.AppConstants.TargetPrintedWidthMeters;

        public string NarrationText =>
            $"{hardwareName}. {fullName}. Fungsi: {function} Contoh: {contextualExample}";

        public HotspotData FindHotspot(string id) => hotspots.Find(h => h.hotspotId == id);
    }
}
