using System;
using System.Collections.Generic;
using ComputerExplorer.Core;
using UnityEngine;

namespace ComputerExplorer.Data
{
    public enum HardwareCategory { Processing, Memory, Storage, Input, Output, Architecture }

    public static class HardwareCategoryExtensions
    {
        public static string DisplayName(this HardwareCategory c) => c switch
        {
            HardwareCategory.Processing => Loc.T("Pemrosesan", "Processing"),
            HardwareCategory.Memory => Loc.T("Memori", "Memory"),
            HardwareCategory.Storage => Loc.T("Penyimpanan", "Storage"),
            HardwareCategory.Input => "Input",
            HardwareCategory.Output => "Output",
            HardwareCategory.Architecture => Loc.T("Arsitektur", "Architecture"),
            _ => c.ToString()
        };
    }

    /// <summary>An interactive point on a 3D hardware model (e.g. ALU on the CPU).</summary>
    [Serializable]
    public class HotspotData
    {
        public string hotspotId;
        public string label;
        [TextArea(2, 6)] public string description;
        [Header("English")]
        public string labelEn;
        [TextArea(2, 6)] public string descriptionEn;
        [Tooltip("Position relative to the model root, in model units (model is ~1 unit wide).")]
        public Vector3 localPosition;
        public AudioClip narration;
        public AudioClip narrationEn;

        public string Label => Loc.T(label, labelEn);
        public string Description => Loc.T(description, descriptionEn);
        public AudioClip Clip => Loc.Clip(narration, narrationEn);
    }

    /// <summary>
    /// Educational content for one hardware item, in Bahasa Indonesia with English in the "…En" fields.
    /// Screens read the language-aware properties (FullName, Function, …). Edit these assets instead of code.
    /// </summary>
    [CreateAssetMenu(menuName = "Computer Explorer/Hardware Data", fileName = "Hardware_")]
    public class HardwareData : ScriptableObject
    {
        public string hardwareId;
        [Tooltip("Short name, the same in both languages (CPU, RAM, …).")]
        public string hardwareName;
        public string fullName;
        public HardwareCategory category;
        [TextArea(2, 4)] public string shortDescription;
        [TextArea(3, 8)] public string detailedDescription;
        [TextArea(2, 4)] public string function;
        [TextArea(2, 6)] public string contextualExample;

        [Header("English")]
        public string fullNameEn;
        [TextArea(2, 4)] public string shortDescriptionEn;
        [TextArea(3, 8)] public string detailedDescriptionEn;
        [TextArea(2, 4)] public string functionEn;
        [TextArea(2, 6)] public string contextualExampleEn;

        [Header("Presentation")]
        [Tooltip("Optional. If empty, a procedural model is generated by HardwareModelFactory.")]
        public GameObject modelPrefab;
        [Tooltip("Optional recorded narration. If empty, Android Text-to-Speech reads the text.")]
        public AudioClip narration;
        public AudioClip narrationEn;
        public Sprite icon;
        [Tooltip("Icon file name in Resources/Icons, used when no sprite is assigned.")]
        public string iconName = "cpu";

        public List<HotspotData> hotspots = new List<HotspotData>();

        [Header("AR Target (Vuforia)")]
        [Tooltip("Target name in the Vuforia database, or name of the image in Resources/ARTargets.")]
        public string arTargetName;
        [Tooltip("Optional runtime image target. Must be readable (set automatically by AssetImportSettings).")]
        public Texture2D arTargetImage;
        public float printedWidthMeters = AppConstants.TargetPrintedWidthMeters;

        // ------------------------------------------------------------------ language-aware accessors
        public string Name => hardwareName;
        public string FullName => Loc.T(fullName, fullNameEn);
        public string ShortDescription => Loc.T(shortDescription, shortDescriptionEn);
        public string DetailedDescription => Loc.T(detailedDescription, detailedDescriptionEn);
        public string Function => Loc.T(function, functionEn);
        public string ContextualExample => Loc.T(contextualExample, contextualExampleEn);
        public AudioClip NarrationClip => Loc.Clip(narration, narrationEn);

        public string NarrationText =>
            $"{hardwareName}. {FullName}. {Loc.T("Fungsi", "Function")}: {Function} {Loc.T("Contoh", "Example")}: {ContextualExample}";

        public HotspotData FindHotspot(string id) => hotspots.Find(h => h.hotspotId == id);
    }
}
